config/routes.rb
Rails.application.routes.draw do
  resources :pizzas

  root "pizzas#home"

end

app/models/pizza.rb
class Pizza < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_action :set_pizza, only: [:show, :edit, :update, :destroy]

 def home
 end

  # GET /pizzas
  # GET /pizzas.json
  def index
    @pizzas = Pizza.all
  end

  # GET /pizzas/1
  # GET /pizzas/1.json
  def show
  end

  # GET /pizzas/new
  def new
    @pizza = Pizza.new
  end

  # GET /pizzas/1/edit
  def edit
  end

  # POST /pizzas
  # POST /pizzas.json
  def create
    @pizza = Pizza.new(pizza_params)

    respond_to do |format|
      if @pizza.save
        format.html { redirect_to @pizza, notice: 'Pizza was successfully created.' }
        format.json { render :show, status: :created, location: @pizza }
      else
        format.html { render :new }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pizzas/1
  # PATCH/PUT /pizzas/1.json
  def update
    respond_to do |format|
      if @pizza.update(pizza_params)
        format.html { redirect_to @pizza, notice: 'Pizza was successfully updated.' }
        format.json { render :show, status: :ok, location: @pizza }
      else
        format.html { render :edit }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzas/1
  # DELETE /pizzas/1.json
  def destroy
    @pizza.destroy
    respond_to do |format|
      format.html { redirect_to pizzas_url, notice: 'Pizza was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pizza
      @pizza = Pizza.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pizza_params
      params.require(:pizza).permit(:name, :crust, :sauce, :toppings, :cost, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Pizza Vengence</title>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">


  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Pizzas", pizzas_url %></li>
        <li><a href="#">About</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>


  <div class="landing">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  </div>
</body>
</html>

app/views/pizzas/_form.html.erb
<%= form_for(@pizza) do |f| %>
  <% if @pizza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pizza.errors.count, "error") %> prohibited this pizza from being saved:</h2>

      <ul>
      <% @pizza.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :crust %><br>
    <%= f.text_field :crust %>
  </div>
  <div class="field">
    <%= f.label :sauce %><br>
    <%= f.text_field :sauce %>
  </div>
  <div class="field">
    <%= f.label :toppings %><br>
    <%= f.text_area :toppings %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.number_field :cost %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pizzas/edit.html.erb
<h1>Editing Pizza</h1>

<%= render 'form' %>

<%= link_to 'Show', @pizza %> |
<%= link_to 'Back', pizzas_path %>

app/views/pizzas/home.html.erb
<html>
<body>
<div id="container">
    <div id="header">
        <div class="jumbotron"> 
          <div class="container">
            <h1>Pizza. With a Vengence.</h1>
            <p>Murder that slice. Enjoy a violently delicious meal at Pizza Vengence. <br>Satisfaction gauranteed.</p>
            <p><%= link_to "Check out our hot stuff", pizzas_path, class: "btn btn-warning" %></p>
        </div>
    </div>
</div>

<div class="row-fluid">
    <div class="col-sm-2 col-md-9">
        <div class="pizza">
            <p>Get ready to eat the best pizza ever.</p>
        </div>
    </div>

<div class="col-sm-2 col-md-3"> 
    <div id="sidebar">
        <h1>Why We're Better</h1>
        <h2>You know you want us.</h2>
        <p>Our pizzas only have the good stuff. We like them round, thick, and saucy. Fresh till consumption 110% all natural ingredients.</p>

        <ul class="list-group">
          <h3>Real Talk:</h3>
            <li class="list-group-item">We've been making pizza since 2010. That's longer than you've ever held a job.</li>
            <li class="list-group-item">We sing to the dough every night to ensure it can dance in your mouth when it reaches maturity.</li>
            <li class="list-group-item">We put the sauce on top because hot, juicy goodness is the first thing you should feel after a long day at work.</li>
            <li class="list-group-item">We might be offensive, but even your grandmother wants a slice of this. Seriously. Ask her.</li>

        </ul>
      </div>
    </div>
</div>

  <div class="row-fluid">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
     <img src="http://www.chowstatic.com/assets/2014/09/28068_buffalo_chicken_wings.jpg" width="600">
      <div class="caption">
        <h3>Siracha Glazed Wings</h3>
        <p>These wings pack a serious punch.</p>
        <p><a href="#" class="btn btn-warning" role="button">More Wings</a></p>
      </div>
    </div>
  </div>
</div>
<div class="row-fluid">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
     <img src="http://i.kinja-img.com/gawker-media/image/upload/wr68salkokqxyadg8ezw.png">
      <div class="caption">
        <h3>Waffle Mozzarella Bites</h3>
        <p>Fried, cheesey goodness.</p>
        <p><a href="#" class="btn btn-warning" role="button">More Apps</a></p>
      </div>
    </div>
  </div>
</div>
<div class="row-fluid">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
       <img src="http://www.cakebakeandsweets.com/sydney/wp-content/uploads/sites/2/2015/08/Smores-Pizza.jpg">
      <div class="caption">
        <h3>Gimme Smore</h3>
        <p>Gooey chocolate and marshmallow pie.</p>
        <p><a href="#" class="btn btn-warning" role="button">More Desserts</a></p>
      </div>
    </div>
  </div>
</div>
</div>

<div class="panel panel-inverse">
  <div class="panel-heading">
    <h3 class="panel-title">Who We Are</h3>
  </div>
  <div class="panel-body">
    Bacon ipsum dolor amet shank salami hamburger, venison leberkas ribeye jerky sausage bresaola pork t-bone. Tenderloin pork loin drumstick bacon, porchetta capicola pork. Kielbasa alcatra beef andouille shoulder. Alcatra turducken hamburger, ribeye kevin prosciutto capicola sausage salami biltong.
  </div>
</div>
    
</div>
    <div id="footer">
        <footer>
    <div class="footer" id="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> Order </h3>
                    <ul>
                        <li> <a href="#"> Pizza </a> </li>
                        <li> <a href="#"> Pasta </a> </li>
                        <li> <a href="#"> Wings </a> </li>
                        <li> <a href="#"> Sides </a> </li>
                        <li> <a href="#"> Dipping Sauces </a> </li>
                        <li> <a href="#"> Drinks </a> </li>
                        <li> <a href="#"> Desserts </a> </li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> About Us </h3>
                    <ul>
                        <li> <a href="#"> Our Story </a> </li>
                        <li> <a href="#"> Vengence Life Blog </a> </li>
                        <li> <a href="#"> Careers </a> </li>
                        <li> <a href="#"> Ingredients </a> </li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> Customer Service </h3>
                    <ul>
                        <li> <a href="#"> Contact Us </a> </li>
                        <li> <a href="#"> Find a Store </a> </li>
                        <li> <a href="#"> FAQs </a> </li>
                    </ul>
                </div>
                <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                    <h3> My Account </h3>
                    <ul>
                        <li> <a href="#"> Create an Account </a> </li>
                        <li> <a href="#"> Sign In </a> </li>
                    </ul>
                </div>
                <div class="col-lg-3  col-md-3 col-sm-6 col-xs-12 ">
                    <h3> Connect With Us </h3>
                    <ul>
                        <li>
                            <div class="input-append newsletter-box text-center">
                                <input type="text" class="full text-center" placeholder="Email ">
                                <button class="btn  bg-gray" type="button"> Sign Up NOW <i class="fa fa-long-arrow-right"> </i> </button>
                            </div>
                        </li>
                    </ul>
                    <ul class="social">
                        <li> <a href="#"> <i class=" fa fa-facebook">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-twitter">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-google-plus">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-pinterest">   </i> </a> </li>
                        <li> <a href="#"> <i class="fa fa-youtube">   </i> </a> </li>
                    </ul>
                </div>
            </div>
            <!--/.row--> 
        </div>
        <!--/.container--> 
    </div>
    <!--/.footer-->
    
    <div class="footer-bottom">
        <div class="container">
            <p class="pull-left"> Copyright © Footer E-commerce Plugin 2014. All right reserved. </p>
            <div class="pull-right">
                <ul class="nav nav-pills payments">
                  <li><i class="fa fa-cc-visa"></i></li>
                    <li><i class="fa fa-cc-mastercard"></i></li>
                    <li><i class="fa fa-cc-amex"></i></li>
                    <li><i class="fa fa-cc-paypal"></i></li>
                </ul> 
            </div>
        </div>
    </div>
    <!--/.footer-bottom--> 
</footer>
    </div>
</div>
</body>
</html>

app/views/pizzas/index.html.erb
<h1>All of our Pizzas</h1>
<div class="row">
  <% @pizzas.each do |pizza| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="<%= pizza.image %>">
      <div class="caption">
        <h3><%= pizza.name %></h3>
        <h3>Cost: $<%= pizza.cost %></h3>
        <%= link_to "More Info", pizza, class: "btn btn-default" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

<br>

<% link_to "New Pizza", new_pizza_path, class: "btn btn-primary" %>

app/views/pizzas/new.html.erb
<h1>New Pizza</h1>

<%= render 'form' %>

<%= link_to 'Back', pizzas_path %>

app/views/pizzas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pizza.name %>
</p>

<p>
  <strong>Crust:</strong>
  <%= @pizza.crust %>
</p>

<p>
  <strong>Sauce:</strong>
  <%= @pizza.sauce %>
</p>

<p>
  <strong>Toppings:</strong>
  <%= @pizza.toppings %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @pizza.cost %>
</p>

<p>
  <strong>Image:</strong>
  <%= @pizza.image %>
</p>

<%= link_to 'Edit', edit_pizza_path(@pizza) %> |
<%= link_to 'Back', pizzas_path %>